on:
  workflow_dispatch:
  push:
    branches:
      - master
name: 🚀 Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build 🔨
        run: |
          npm ci
          npm run build

      - name: FTP Upload 📂
        env:
          FTP_PASSWORD: ${{ secrets.ftp_password }}
        run: |
          sudo apt-get install -y lftp
          lftp -c "
            set ftp:passive-mode yes;
            set net:max-retries 5;
            set net:reconnect-interval-base 5;
            set net:reconnect-interval-multiplier 1;
            open ftp://u429394839.EmberInstruments:$FTP_PASSWORD@ftp.emberinstruments.com;
            mirror --reverse --delete --verbose ./out/ /;
            bye
          "
