on:
  workflow_dispatch:
  push:
    branches:
      - master
name: 🚀 Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v2-beta
        with:
          node-version: "20.2.0"

      - name: Build 🔨
        run: |
          npm install
          npm run build
      - name: FTP Upload 📂
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.emberinstruments.com
          username: u429394839.EmberInstruments
          password: ${{ secrets.ftp_password }}
          local-dir: ./out/
          dangerous-clean-slate: true
